### ISSUE TITLE
Camera resolution is low

### ISSUE THREAD

**Issue by ahmedorabi94** [javaherisaber/MLBarcodeScanner#1]
can you check how the camera resolution should be good?

**Comment by javaherisaber** [comment]
@ahmedorabi94 
The previous resolution was set to the default value (640 ✕ 480)
But you can set a target resolution for the scanner like this:
https://github.com/javaherisaber/MLBarcodeScanner/blob/ed15e20bf023f7a2ae69c39733738bce5f64fac0/app/src/main/java/nl/storegear/android/mlbarcodescanner/MainActivity.kt#L101

Caveat: Setting high resolution will impact performance and makes the scanner slow

**Comment by javaherisaber** [comment]
@ahmedorabi94 
I've created a package with more simplified usage 
you can check here:
https://jitpack.io/#javaherisaber/MLBarcodeScanner

**Comment by ahmedorabi94** [comment]
Thanks, it works perfectly for me
