### ISSUE TITLE
Bad preview performance

### ISSUE THREAD

**Issue by micstepper** [javaherisaber/MLBarcodeScanner#2]
Hello, the preview performance is really bad. The preview hangs heavily and drags the image. Any ideas to fix this?

**Comment by micstepper** [comment]
Its because of this value: private val targetResolution: Size = Size(768, 1024)

It would be great to make it adustable like the other params.

**Comment by javaherisaber** [comment]
@micstepper 
It's actually the default value
You can pass your own value to MLBarcodeScanner instance
take a look at this class

https://github.com/javaherisaber/MLBarcodeScanner/blob/a7e29c7045f0962709c6369eacd8e92e9a4a627b/app/src/main/java/nl/storegear/android/mlbarcodescanner/MainActivity.kt#L28

**Comment by micstepper** [comment]
Hey, my fault, I tried to do this before, but did it wrong.

**Comment by micstepper** [comment]
But I cant get it run more fluent. Like I wrote before the camera preview hangs a lot. Any ideas?

**Comment by micstepper** [comment]
Maybe instead of using targetResolution you could use targetAspectRatio? Or why did you use targetResolution in preview?

**Comment by javaherisaber** [comment]
@micstepper 
According to the documentation:
> It is not allowed to set both target aspect ratio and target resolution on the same use case. Attempting so will throw an IllegalArgumentException when building the Config

It would help if you tuned the targetResolution value to find out what will actually fit with your usecase
Even if I did not set targetResolution its default value is 360 * 640 which will result in blurry vision

Btw performance of this API is low on Debug build
Do you experience the same issues on Release build?

**Comment by micstepper** [comment]
@javaherisaber I tried that before, and yes it runs much faster, but the image looks really blurry. Using the Google Material Design Showcase I do not have this issues...I tracked it down to the point where the image is tranformed to a bitmap. Thats where the slowing down affects takes place. Why exactly do we need this transformation?

**Comment by javaherisaber** [comment]
To limit capturing the barcode inside the focus area shown as a rectangle icon, we need to know the exact width and height of 
the barcode itself. this was the solution I came up with.

Google sample also is transforming into bitmap (and actually much more slower and blurry than my adjusted package):

https://github.com/googlesamples/mlkit/blob/cdaf07eb180610ef816a46b5f6365c45af627a74/android/vision-quickstart/app/src/main/java/com/google/mlkit/vision/demo/kotlin/VisionProcessorBase.kt#L217

Isn't it capturing any of your barcodes properly?
aside from the blurriness

**Comment by javaherisaber** [comment]
Closing this inactive issue, feel free to reopen it if there is still a question remaining.
